### PR TITLE
Update to clap 4

### PR DESCRIPTION
**Pull request by w0xel**
Hey, I tried to update clap to version 4 in the lib.

The conversion of any field to a string is a bit wonky... maybe you have a better idea?

### CODE REVIEW

**Comment by bnjjj** [comment]
Hey thanks ! I also had a wip version on my laptop but didn't find time to finish it. Are you able to compile and launch all examples ?

**Comment by w0xel** [comment]
Good point, done and fixed that now. `cargo test` also runs successfully, when activating all features. I had to make small changes to the examples/tests though, that you might want to look into.

Especially I couldn't get `--help` to work with `ignore_errors(true)` as used in the `clap_derive` example.

**Review by bnjjj — APPROVED** [review]
LGTM I need to double check locally tomorrow ! Ping me again if I forget ! Thanks a lot

**Comment by bnjjj** [comment]
Thanks a lot @w0xel, it has been release on v`0.8.0` on crates.io

**Pull request merged**
